-- Autocmd は VeryLazy イベントで自動的に読み込まれます
-- 常に設定されるデフォルトの autocmd: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- 追加の autocmd はここに記述してください
-- `vim.api.nvim_create_autocmd` を使って追加できます
--
-- 既存の autocmd をグループ名で削除することもできます（デフォルトは `lazyvim_` が接頭辞）
-- 例: vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
